services:
  db:
    image: postgres:17
    container_name: map-crime-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mapcrime_db
    ports:
      - "5432:5432"
